default_config:
tts:
  - platform: google_translate
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
recorder:
  purge_keep_days: 30
  commit_interval: 3
  db_url: postgresql://home-assistant:ftg7mx7or5epbytn2bpd@postgres:5432/home-assistant?sslmode=disable
google_assistant: !include google_assistant.yaml
http: !include http.yaml
