---
# Homepage Settings
# https://gethomepage.dev/configs/settings/

title: Punsvik Homelab

theme: dark
color: slate

background:
  image: https://images.unsplash.com/photo-1475274047050-1d0c0975c63e?w=1920
  blur: sm
  opacity: 50

cardBlur: md

favicon: https://raw.githubusercontent.com/gethomepage/homepage/main/public/homepage.png

headerStyle: clean

layout:
  Home:
    style: row
    columns: 5
  Tools:
    style: row
    columns: 5
  Infrastructure:
    style: row
    columns: 7
  Backend:
    style: row
    columns: 3
  Inactive Apps:
    style: row
    columns: 4
    initiallyCollapsed: true
