http:
  routers:
    tandoor:
      rule: "Host(`tandoor.punsvik.net`)"
      entryPoints:
        - websecure
      service: tandoor-svc
      tls:
        certResolver: le
      middlewares:
        - security-headers@file

  services:
    tandoor-svc:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://192.168.1.4:30290"
